# Generated by Django 6.0.3 on 2026-03-21 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ativo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        help_text="Categoria ou tipo que classifica este ativo (ex.: 'Sistema de TI', 'Documento', 'Processo').",
                        max_length=200,
                    ),
                ),
                (
                    "confidencialidade",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Grau de sensibilidade das informações deste ativo. Uma pontuação mais alta indica maior prejuízo caso os dados sejam divulgados sem autorização.",
                        verbose_name="Confidencialidade (C)",
                    ),
                ),
                (
                    "integridade",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Grau de criticalidade do dado deste ativo. Uma pontuação mais alta indica maior dano se os dados forem modificados ou corrompidos.",
                        verbose_name="Integridade (I)",
                    ),
                ),
                (
                    "disponibilidade",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Grau de importância do acesso a este ativo quando necessário. Uma pontuação mais alta indica impacto mais severo se o ativo se tornar indisponível.",
                        verbose_name="Disponibilidade (D)",
                    ),
                ),
                (
                    "privacidade",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="O grau em que este ativo lida com dados pessoais sujeitos a regulamentações de privacidade. Uma pontuação mais alta indica maior exposição a obrigações e riscos relacionados à privacidade.",
                        verbose_name="Privacidade (P)",
                    ),
                ),
                (
                    "peso_cidp",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Peso composto CIDP calculado a partir das quatro pontuações de dimensão acima. ",
                        max_digits=5,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ativo",
                "verbose_name_plural": "Ativos",
            },
        ),
        migrations.CreateModel(
            name="Consequencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "peso",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Peso numérico atribuído a este nível de severidade. Valores mais altos indicam maior impacto e elevam o valor geral de risco.",
                        max_digits=5,
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        help_text="Explicação detalhada do que este nível de impacto representa na prática."
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("muito_alto", "Muito Alto"),
                            ("alto", "Alto"),
                            ("medio", "Médio"),
                            ("baixo", "Baixo"),
                            ("muito_baixo", "Muito Baixo"),
                        ],
                        help_text="Categoria de severidade que classifica este nível de consequência.",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Consequência",
                "verbose_name_plural": "Consequências",
            },
        ),
        migrations.CreateModel(
            name="Nivel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("inerente", "Inerente"), ("residual", "Residual")],
                        help_text="Define se este nível é utilizado no score de risco inerente (antes dos controles) ou no score de risco residual (após os controles).",
                        max_length=10,
                    ),
                ),
                (
                    "peso",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Peso numérico que representa este nível de risco dentro da matriz de risco da organização.",
                        max_digits=5,
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        help_text="Rótulo legível por humanos para este nível de risco (e.g. 'Crítico', 'Alto', 'Médio', 'Baixo').",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Nível",
                "verbose_name_plural": "Níveis",
            },
        ),
        migrations.CreateModel(
            name="Probabilidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "peso",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Peso numérico para este nível de probabilidade. Valores mais altos indicam maior chance de ocorrência e elevam o score geral de risco.",
                        max_digits=5,
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        help_text="Explicação do que este nível de probabilidade representa (e.g. faixa de frequência, orientação qualitativa)."
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("muito_alta", "Muito Alta"),
                            ("alta", "Alta"),
                            ("media", "Média"),
                            ("baixa", "Baixa"),
                            ("muito_baixa", "Muito Baixa"),
                            ("frequente", "Frequente"),
                        ],
                        help_text="Categoria de probabilidade que agrupa este nível de probabilidade.",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Probabilidade",
                "verbose_name_plural": "Probabilidades",
            },
        ),
        migrations.CreateModel(
            name="Tratamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_tratamento",
                    models.CharField(
                        choices=[
                            ("aceitar", "Aceitar"),
                            ("mitigar", "Mitigar (Modificar)"),
                            ("evitar", "Evitar"),
                            ("compartilhar", "Compartilhar"),
                        ],
                        help_text="Estratégia de resposta ao risco selecionada para este tratamento.",
                        max_length=20,
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        help_text="Detalhes de implementação deste tratamento: quais ações serão tomadas, quem é o responsável e quaisquer prazos ou decisões relevantes."
                    ),
                ),
            ],
            options={
                "verbose_name": "Tratamento",
                "verbose_name_plural": "Tratamentos",
            },
        ),
        migrations.CreateModel(
            name="Ameaca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        help_text="Descrição detalhada do cenário de ameaça, incluindo como ele poderia ser acionado e por quem."
                    ),
                ),
                (
                    "ativo",
                    models.ForeignKey(
                        help_text="O ativo que esta ameaça tem como alvo.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ameacas",
                        to="ismsapp.ativo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ameaça",
                "verbose_name_plural": "Ameaças",
            },
        ),
        migrations.CreateModel(
            name="Risco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("inerente", "Inerente"), ("residual", "Residual")],
                        help_text="Indica se este registro está rotulado como uma avaliação de risco inerente ou residual.",
                        max_length=10,
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        help_text="Descrição completa do cenário de risco: o que poderia acontecer, por quê, e qual seria o impacto."
                    ),
                ),
                (
                    "ameacas",
                    models.ManyToManyField(
                        blank=True,
                        help_text="As ameaças que contribuem para este cenário de risco.",
                        related_name="riscos",
                        to="ismsapp.ameaca",
                    ),
                ),
                (
                    "ativo",
                    models.ForeignKey(
                        help_text="O ativo que é exposto a este risco.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="riscos",
                        to="ismsapp.ativo",
                    ),
                ),
                (
                    "consequencia_inerente",
                    models.ForeignKey(
                        blank=True,
                        help_text="A severidade do impacto se este risco materializar e não houver controles em vigor.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="riscos_inerentes",
                        to="ismsapp.consequencia",
                    ),
                ),
                (
                    "consequencia_residual",
                    models.ForeignKey(
                        blank=True,
                        help_text="A severidade do impacto após a aplicação dos controles ou mitigações planejados.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="riscos_residuais",
                        to="ismsapp.consequencia",
                    ),
                ),
                (
                    "nivel_inerente",
                    models.ForeignKey(
                        blank=True,
                        help_text="O nível geral de risco inerente derivado da combinação da consequência e da probabilidade inerentes (ex.: 'Crítico', 'Alto').",
                        limit_choices_to={"tipo": "inerente"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="riscos_inerentes",
                        to="ismsapp.nivel",
                    ),
                ),
                (
                    "nivel_residual",
                    models.ForeignKey(
                        blank=True,
                        help_text="O nível geral de risco residual derivado da combinação da consequência e da probabilidade residuais. Este é o nível alvo que a organização pretende alcançar por meio do tratamento.",
                        limit_choices_to={"tipo": "residual"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="riscos_residuais",
                        to="ismsapp.nivel",
                    ),
                ),
                (
                    "probabilidade_inerente",
                    models.ForeignKey(
                        blank=True,
                        help_text="A probabilidade de este risco ocorrer sem qualquer controle em vigor.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="riscos_inerentes",
                        to="ismsapp.probabilidade",
                    ),
                ),
                (
                    "probabilidade_residual",
                    models.ForeignKey(
                        blank=True,
                        help_text="A probabilidade de este risco ainda ocorrer após a aplicação dos controles.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="riscos_residuais",
                        to="ismsapp.probabilidade",
                    ),
                ),
                (
                    "tratamentos",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Os planos de tratamento selecionados para lidar com este risco. Mais de um tratamento pode ser aplicado (e.g. mitigar + compartilhar).",
                        related_name="riscos",
                        to="ismsapp.tratamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Risco",
                "verbose_name_plural": "Riscos",
            },
        ),
        migrations.CreateModel(
            name="Controle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descrição opcional ou código de referência do controle (ex.: 'A.9.1.1 – Política de controle de acesso').",
                    ),
                ),
                (
                    "tratamento",
                    models.ForeignKey(
                        help_text="O plano de tratamento ao qual este controle pertence.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controles",
                        to="ismsapp.tratamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Controle",
                "verbose_name_plural": "Controles",
            },
        ),
        migrations.CreateModel(
            name="Vulnerabilidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descrição opcional da vulnerabilidade específica e como ela poderia ser explorada.",
                    ),
                ),
                (
                    "ameaca",
                    models.ForeignKey(
                        help_text="A ameaça que poderia explorar esta vulnerabilidade.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vulnerabilidades",
                        to="ismsapp.ameaca",
                    ),
                ),
                (
                    "ativo",
                    models.ForeignKey(
                        help_text="O ativo que contém esta vulnerabilidade.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vulnerabilidades",
                        to="ismsapp.ativo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vulnerabilidade",
                "verbose_name_plural": "Vulnerabilidades",
                "unique_together": {("ativo", "ameaca")},
            },
        ),
    ]
