# Generated by Django 6.0.3 on 2026-03-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ismsapp", "0002_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaAtivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome da categoria. Deve ser único no sistema.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("primario", "Primário"), ("suporte", "De Suporte")],
                        help_text="Tipo do ativo: 'Primário' para ativos com valor direto ao negócio (ex.: informações, serviços); 'De Suporte' para infraestrutura que sustenta os ativos primários (ex.: hardware, software, pessoas).",
                        max_length=10,
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        help_text="Descrição detalhada da categoria e dos ativos que ela engloba."
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora em que a categoria foi registrada no sistema.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria de Ativo",
                "verbose_name_plural": "Categorias de Ativos",
                "ordering": ["tipo", "nome"],
            },
        ),
    ]
