# Generated by Django 6.0.3 on 2026-03-23 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ismsapp", "0003_categoriaativo"),
    ]

    operations = [
        migrations.AddField(
            model_name="ativo",
            name="descricao",
            field=models.TextField(
                blank=True,
                help_text="Descrição detalhada da finalidade e características do ativo.",
            ),
        ),
        migrations.AddField(
            model_name="ativo",
            name="interdependencias",
            field=models.TextField(
                blank=True,
                help_text="Ativos necessários para o funcionamento deste ativo.",
            ),
        ),
        migrations.AddField(
            model_name="ativo",
            name="nome",
            field=models.CharField(
                default="Ativo",
                help_text="Nome único ou identificador do ativo (ex.: 'Servidor de Banco de Dados Prod-01').",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="ativo",
            name="responsavel",
            field=models.CharField(
                default="Responsável",
                help_text="Nome ou departamento responsável por este ativo.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="ativo",
            name="categoria",
            field=models.ForeignKey(
                help_text="Categoria que classifica este ativo.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ativos",
                to="ismsapp.categoriaativo",
            ),
        ),
    ]
