# Generated by Django 6.0.3 on 2026-03-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ismsapp", "0004_ativo_descricao_ativo_interdependencias_ativo_nome_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ativo",
            name="interdependencias",
        ),
        migrations.AddField(
            model_name="ativo",
            name="interdependencias",
            field=models.ManyToManyField(
                blank=True,
                help_text="Ativos necessários para o funcionamento deste ativo.",
                related_name="dependentes",
                to="ismsapp.ativo",
            ),
        ),
    ]
