# Generated by Django 6.0.3 on 2026-03-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ismsapp", "0005_remove_ativo_interdependencias_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CriterioAvaliacaoRisco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "escala_probabilidade_1",
                    models.CharField(
                        default="Muito Baixo",
                        help_text="Descrição do nível 1 de probabilidade",
                        max_length=100,
                    ),
                ),
                (
                    "escala_probabilidade_2",
                    models.CharField(
                        default="Baixo",
                        help_text="Descrição do nível 2 de probabilidade",
                        max_length=100,
                    ),
                ),
                (
                    "escala_probabilidade_3",
                    models.CharField(
                        default="Médio",
                        help_text="Descrição do nível 3 de probabilidade",
                        max_length=100,
                    ),
                ),
                (
                    "escala_probabilidade_4",
                    models.CharField(
                        default="Alto",
                        help_text="Descrição do nível 4 de probabilidade",
                        max_length=100,
                    ),
                ),
                (
                    "escala_probabilidade_5",
                    models.CharField(
                        default="Muito Alto",
                        help_text="Descrição do nível 5 de probabilidade",
                        max_length=100,
                    ),
                ),
                (
                    "escala_consequencia_1",
                    models.CharField(
                        default="Muito Baixo",
                        help_text="Descrição do nível 1 de consequência",
                        max_length=100,
                    ),
                ),
                (
                    "escala_consequencia_2",
                    models.CharField(
                        default="Baixo",
                        help_text="Descrição do nível 2 de consequência",
                        max_length=100,
                    ),
                ),
                (
                    "escala_consequencia_3",
                    models.CharField(
                        default="Médio",
                        help_text="Descrição do nível 3 de consequência",
                        max_length=100,
                    ),
                ),
                (
                    "escala_consequencia_4",
                    models.CharField(
                        default="Alto",
                        help_text="Descrição do nível 4 de consequência",
                        max_length=100,
                    ),
                ),
                (
                    "escala_consequencia_5",
                    models.CharField(
                        default="Muito Alto",
                        help_text="Descrição do nível 5 de consequência",
                        max_length=100,
                    ),
                ),
                (
                    "apetite_risco",
                    models.CharField(
                        choices=[
                            ("baixo", "Baixo"),
                            ("moderado", "Moderado"),
                            ("alto", "Alto"),
                        ],
                        default="moderado",
                        help_text="Nível de apetite ao risco organizacional",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Critério de Avaliação de Risco",
                "verbose_name_plural": "Critérios de Avaliação de Risco",
            },
        ),
    ]
