# Generated by Django 6.0.3 on 2026-03-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ismsapp", "0006_criterioavaliacaorisco"),
    ]

    operations = [
        migrations.AddField(
            model_name="risco",
            name="impactos",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Perdas potenciais e impactos se o risco se materializar (financeiros, operacionais, reputacionais, etc.).",
            ),
        ),
        migrations.AddField(
            model_name="risco",
            name="nome",
            field=models.CharField(
                default="Risco sem nome",
                help_text="Nome ou título do risco.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="risco",
            name="valor_risco_inerente",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Valor numérico do risco inerente (probabilidade × consequência).",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="risco",
            name="valor_risco_residual",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Valor numérico do risco residual após aplicação dos controles.",
                max_digits=5,
                null=True,
            ),
        ),
    ]
