# Generated by Django 6.0.3 on 2026-03-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ismsapp",
            "0007_risco_impactos_risco_nome_risco_valor_risco_inerente_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="risco",
            name="nome",
            field=models.CharField(
                help_text="Nome ou título do risco.", max_length=255
            ),
        ),
    ]
