# Generated by Django 6.0.3 on 2026-03-27 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ismsapp", "0009_add_risk_evaluation_decision"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="risco",
            name="auditor_avaliacao",
        ),
        migrations.RemoveField(
            model_name="risco",
            name="data_avaliacao",
        ),
    ]
