# Generated by Django 6.0.3 on 2026-03-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ismsapp", "0010_remove_risco_auditor_avaliacao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tratamento",
            name="prazo",
            field=models.DateField(
                blank=True,
                help_text="Prazo para implementação deste tratamento.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tratamento",
            name="reducao_impacto",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Porcentagem esperada de redução no impacto/consequência do risco (0-100).",
            ),
        ),
        migrations.AddField(
            model_name="tratamento",
            name="reducao_probabilidade",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Porcentagem esperada de redução na probabilidade do risco (0-100).",
            ),
        ),
        migrations.AddField(
            model_name="tratamento",
            name="responsavel",
            field=models.CharField(
                blank=True,
                help_text="Nome ou departamento responsável pela implementação deste tratamento.",
                max_length=200,
            ),
        ),
    ]
