# Generated by Django 6.0.3 on 2026-03-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ismsapp", "0011_tratamento_prazo_tratamento_reducao_impacto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tratamento",
            name="tipo_tratamento",
            field=models.CharField(
                choices=[
                    ("aceitar", "Aceitar"),
                    ("mitigar", "Mitigar"),
                    ("evitar", "Evitar"),
                    ("compartilhar", "Compartilhar"),
                ],
                help_text="Estratégia de resposta ao risco selecionada para este tratamento.",
                max_length=20,
            ),
        ),
    ]
