# Generated by Django 6.0.3 on 2026-03-27 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ismsapp", "0012_alter_tratamento_tipo_tratamento"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="tratamento",
            name="responsavel",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuário responsável pela implementação deste tratamento.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tratamentos_responsavel",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
