# Generated by Django 6.0.3 on 2026-03-28 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ismsapp", "0013_alter_tratamento_responsavel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Incidente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_incidente",
                    models.CharField(
                        help_text="Identificador único do incidente (ex: INC-2023-001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        help_text="Descrição detalhada da natureza do incidente observado."
                    ),
                ),
                (
                    "data_incidente",
                    models.DateField(help_text="Data em que o incidente ocorreu."),
                ),
                (
                    "hora_incidente",
                    models.TimeField(help_text="Hora em que o incidente ocorreu."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registrado", "Registrado"),
                            ("em_investigacao", "Em Investigação"),
                            ("resolvido", "Resolvido"),
                            ("fechado", "Fechado"),
                        ],
                        default="registrado",
                        help_text="Status atual do incidente em seu ciclo de vida.",
                        max_length=20,
                    ),
                ),
                (
                    "data_registro",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora do registro do incidente no sistema.",
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização do incidente.",
                    ),
                ),
                (
                    "relatorio_gerado",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se o relatório final foi gerado para este incidente.",
                    ),
                ),
                (
                    "ativos_afetados",
                    models.ManyToManyField(
                        help_text="Ativos afetados por este incidente.",
                        related_name="incidentes",
                        to="ismsapp.ativo",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuário que registrou este incidente.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidentes_registrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsavel_tratamento",
                    models.ForeignKey(
                        blank=True,
                        help_text="Responsável pelo tratamento e resolução do incidente.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidentes_responsavel",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Incidente",
                "verbose_name_plural": "Incidentes",
                "ordering": ["-data_incidente", "-hora_incidente"],
            },
        ),
        migrations.CreateModel(
            name="RelatórioIncidente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "protocolo",
                    models.CharField(
                        help_text="Identificador único do protocolo do relatório (ex: INC-2023-0892)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "data_emissao",
                    models.DateField(
                        auto_now_add=True, help_text="Data de emissão do relatório."
                    ),
                ),
                (
                    "descricao_evento",
                    models.TextField(
                        help_text="Descrição detalhada do evento de segurança que ocorreu."
                    ),
                ),
                (
                    "ativos_afetados_detalhamento",
                    models.TextField(
                        blank=True,
                        help_text="Detalhamento dos ativos afetados e como foram impactados.",
                    ),
                ),
                (
                    "acoes_realizadas",
                    models.TextField(
                        help_text="Descrição detalhada de todas as ações de remediação realizadas."
                    ),
                ),
                (
                    "analise_causa_raiz",
                    models.TextField(
                        blank=True,
                        help_text="Análise detalhada das causas raiz que levaram ao incidente.",
                    ),
                ),
                (
                    "impacto_financeiro",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Impacto financeiro estimado do incidente.",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "impacto_operacional",
                    models.TextField(
                        blank=True,
                        help_text="Descrição do impacto operacional (ex: indisponibilidade do serviço).",
                    ),
                ),
                (
                    "impacto_imagem",
                    models.TextField(
                        blank=True,
                        help_text="Descrição do impacto à imagem/reputação da organização.",
                    ),
                ),
                (
                    "licoes_aprendidas",
                    models.TextField(
                        blank=True,
                        help_text="Lições principais aprendidas com este incidente para evitar recorrências.",
                    ),
                ),
                (
                    "status_relatorio",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("final", "Final"),
                            ("fechado", "Fechado"),
                        ],
                        default="rascunho",
                        help_text="Status atual do relatório.",
                        max_length=20,
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do relatório.",
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização do relatório.",
                    ),
                ),
                (
                    "incidente",
                    models.OneToOneField(
                        help_text="Incidente que este relatório documenta.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relatorio",
                        to="ismsapp.incidente",
                    ),
                ),
                (
                    "responsavel_tratamento",
                    models.ForeignKey(
                        blank=True,
                        help_text="Responsável pelo tratamento e investigação do incidente.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relatorios_incidentes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Relatório de Incidente",
                "verbose_name_plural": "Relatórios de Incidentes",
                "ordering": ["-data_emissao"],
            },
        ),
    ]
