# Generated by Django 6.0.3 on 2026-03-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ismsapp", "0014_incidente_relatórioincidente"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ameaca",
            name="ativo",
        ),
        migrations.AddField(
            model_name="ameaca",
            name="ativos",
            field=models.ManyToManyField(
                help_text="Os ativos que esta ameaça tem como alvo.",
                related_name="ameacas",
                to="ismsapp.ativo",
            ),
        ),
    ]
