# Generated by Django 6.0.3 on 2026-03-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ismsapp", "0015_remove_ameaca_ativo_ameaca_ativos"),
    ]

    operations = [
        migrations.AddField(
            model_name="vulnerabilidade",
            name="nivel_severidade",
            field=models.CharField(
                choices=[
                    ("critico", "Crítico"),
                    ("alto", "Alto"),
                    ("medio", "Médio"),
                    ("baixo", "Baixo"),
                ],
                default="medio",
                help_text="Nível de severidade da vulnerabilidade.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vulnerabilidade",
            name="prioridade_correcao",
            field=models.CharField(
                choices=[
                    ("urgente", "Urgente"),
                    ("alta", "Alta"),
                    ("media", "Média"),
                    ("baixa", "Baixa"),
                ],
                default="media",
                help_text="Prioridade de correção da vulnerabilidade.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vulnerabilidade",
            name="status",
            field=models.CharField(
                choices=[
                    ("registrada", "Registrada"),
                    ("em_tratamento", "Em Tratamento"),
                    ("resolvida", "Resolvida"),
                    ("descartada", "Descartada"),
                ],
                default="registrada",
                help_text="Status atual da vulnerabilidade.",
                max_length=20,
            ),
        ),
    ]
