# Generated by Django 6.0.3 on 2026-03-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ismsapp", "0016_vulnerabilidade_nivel_severidade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ameaca",
            name="impactos",
            field=models.TextField(
                blank=True,
                help_text="Descrição dos possíveis impactos que poderiam resultar da realização desta ameaça.",
            ),
        ),
    ]
