# Generated by Django 6.0.3 on 2026-03-30 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ismsapp', '0017_ameaca_impactos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_auditoria', models.CharField(
                    choices=[('interna', 'Interna'), ('externa', 'Externa')],
                    help_text='Tipo de auditoria realizada: interna ou externa.',
                    max_length=20
                )),
                ('nome', models.CharField(
                    help_text="Nome ou ID da auditoria (ex: 'AUD-2023-001').",
                    max_length=255
                )),
                ('data_auditoria', models.DateField(
                    help_text='Data em que a auditoria foi realizada.'
                )),
                ('nao_conformidades_identificadas', models.BooleanField(
                    default=False,
                    help_text='Indica se foram identificadas não conformidades durante a auditoria.'
                )),
                ('nao_conformidades', models.TextField(
                    blank=True,
                    help_text='Descrição dos achados e não conformidades identificadas (se houver).'
                )),
                ('plano_acao', models.TextField(
                    blank=True,
                    help_text='Planos de ação para remediação das não conformidades.'
                )),
                ('status', models.CharField(
                    choices=[('pendente', 'Pendente'), ('concluida', 'Concluída')],
                    default='pendente',
                    help_text='Status atual da auditoria.',
                    max_length=20
                )),
                ('data_registro', models.DateTimeField(
                    auto_now_add=True,
                    help_text='Data e hora do registro da auditoria no sistema.'
                )),
                ('data_atualizacao', models.DateTimeField(
                    auto_now=True,
                    help_text='Data e hora da última atualização da auditoria.'
                )),
                ('registrado_por', models.ForeignKey(
                    blank=True,
                    help_text='Usuário que registrou esta auditoria.',
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='auditorias_registradas',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'verbose_name': 'Auditoria',
                'verbose_name_plural': 'Auditorias',
                'ordering': ['-data_auditoria'],
            },
        ),
    ]
