# Generated by Django 6.0.3 on 2026-04-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ismsapp", "0018_auditoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="ameaca",
            name="nome",
            field=models.CharField(
                default="Sem nome",
                help_text="Nome ou título da ameaça (ex: Ransomware Cryptolocker).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="ameaca",
            name="origem",
            field=models.CharField(
                choices=[
                    ("externa", "Externa"),
                    ("interna", "Interna"),
                    ("hibrida", "Híbrida"),
                ],
                default="externa",
                help_text="Origem da ameaça.",
                max_length=50,
            ),
        ),
    ]
