# Generated by Django 6.0.3 on 2026-04-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ismsapp", "0019_ameaca_nome_ameaca_origem"),
    ]

    operations = [
        migrations.AddField(
            model_name="vulnerabilidade",
            name="nome",
            field=models.CharField(
                default="Sem nome",
                help_text="Nome ou título da vulnerabilidade identificada (ex: Falta de validação de entradas).",
                max_length=255,
            ),
        ),
    ]
