# Generated by Django 6.0.3 on 2026-04-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ismsapp", "0020_vulnerabilidade_nome"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vulnerabilidade",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="vulnerabilidade",
            name="ameacas",
            field=models.ManyToManyField(
                help_text="As ameaças que poderiam explorar esta vulnerabilidade.",
                related_name="vulnerabilidades",
                to="ismsapp.ameaca",
            ),
        ),
        migrations.RemoveField(
            model_name="vulnerabilidade",
            name="ameaca",
        ),
    ]
