# Generated by Django 6.0.3 on 2026-04-10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ismsapp", "0021_alter_vulnerabilidade_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ativo",
            name="descricao",
        ),
        migrations.RemoveField(
            model_name="ativo",
            name="interdependencias",
        ),
        migrations.RemoveField(
            model_name="ativo",
            name="responsavel",
        ),
    ]
