# Generated by Django 6.0.3 on 2026-04-10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ismsapp", "0022_remove_ativo_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoriaativo",
            name="criado_em",
        ),
        migrations.RemoveField(
            model_name="categoriaativo",
            name="descricao",
        ),
    ]
