# Generated by Django 6.0.3 on 2026-04-10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ismsapp", "0023_remove_categoria_ativo_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ameaca",
            name="descricao",
        ),
        migrations.RemoveField(
            model_name="ameaca",
            name="impactos",
        ),
        migrations.RemoveField(
            model_name="ameaca",
            name="origem",
        ),
    ]
