# Generated by Django 6.0.3 on 2026-04-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ismsapp", "0024_remove_ameaca_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ameaca",
            name="nome",
            field=models.CharField(
                help_text="Nome ou título da ameaça (ex: Ransomware Cryptolocker).",
                max_length=255,
            ),
        ),
    ]
