# Generated by Django 6.0.3 on 2026-04-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ismsapp", "0035_carregar_iso27001_controles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controle",
            name="nome",
            field=models.CharField(
                help_text="Nome ou título do controle (ex: '5.1 - Políticas de segurança da informação').",
                max_length=255,
            ),
        ),
    ]
